### ISSUE TITLE
Pull Secret lost when using Internet connected bastion to install cluster

### ISSUE THREAD

**Issue by cjnovak98** [cjnovak98/ocp4-disconnected-collection#2]
When running all playbooks, including push images and installing the cluster on an internet connected bastion, at one point I checked my ~/.docker/config.json and it no longer had my pull secret. Only the pull secret for the locally hosted registry.

**Comment by cjnovak98** [comment]
labelled as bug since we should be backing up any currently configured pull secrets. (In case they are managing multiple clusters, or in the test case of deploying multiple clusters or any other odd use case)

**Comment by cjnovak98** [comment]
Discussed this with @mriensch and I think we should be able to make this work with some JSON editing - just gotta see how idempotent we can make it with Ansible. (and how much of a PITA it's going to be)

**Comment by mriensch** [comment]
Fix pushed to issue-10-var-structure [6b5bc0a](https://github.com/cjnovak98/ocp4-disconnected-collection/commit/6b5bc0addf6b91e47c98a72f2afaad59ebee013d) will be part of main once we push it
