### ISSUE TITLE
Need a flag in one of the roles so we can change if it is a connected/disconnected installation.

### ISSUE THREAD

**Issue by cjnovak98** [cjnovak98/ocp4-disconnected-collection#7]
See above. This will help with development of ArgoCD and reduce the burden for creating a registry if we ever use this in pipelines as automated Infra CI/CD.

**Comment by mriensch** [comment]
adding 'connected' vairable which will ommit the imageDigestSource from the install-config. it will still use the pull secret in ~/.docker/config.json

**Comment by cjnovak98** [comment]
This was solved with:
`agent_iso_connected: true`
and:
`mirror_content_pull_mirror: false`
